### ISSUE TITLE
请问如何实现左半圆和右半圆

### ISSUE THREAD

**Issue by wangchengyan** [tanyang93/CycleMenuDemo#1]
要实现可滑动的左半圆和右半圆如下图效果
![image](https://user-images.githubusercontent.com/5567984/39293392-56c126fa-496b-11e8-92fa-2872c0d876e2.png)

**Comment by sunytan** [comment]
> 要实现可滑动的左半圆和右半圆如下图效果
> ![image](https://user-images.githubusercontent.com/5567984/39293392-56c126fa-496b-11e8-92fa-2872c0d876e2.png)
@wangchengyan 
原谅我太懒，这个只要加一个旋转角度就行。已经支持。
